# Generated by Django 5.2.16 on 2026-09-23 18:01

from django.db import migrations

import baserow.core.encoders
import baserow.core.encryption.fields


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0067_graph_element"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogentry",
            name="action_params",
            field=baserow.core.encryption.fields.EncryptedJSONField(
                encoder=baserow.core.encoders.JSONEncoderSupportingDataClasses,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facebookauthprovidermodel",
            name="secret",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="API secret, client secret, or consumer secret",
                max_length=191,
            ),
        ),
        migrations.AlterField(
            model_name="githubauthprovidermodel",
            name="secret",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="API secret, client secret, or consumer secret",
                max_length=191,
            ),
        ),
        migrations.AlterField(
            model_name="githubissuesdatasync",
            name="github_issues_api_token",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The API token used to authenticate requests to GitHub.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="gitlabauthprovidermodel",
            name="secret",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="API secret, client secret, or consumer secret",
                max_length=191,
            ),
        ),
        migrations.AlterField(
            model_name="gitlabissuesdatasync",
            name="gitlab_access_token",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The API access token used to authenticate requests to GitLab.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="googleauthprovidermodel",
            name="secret",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="API secret, client secret, or consumer secret",
                max_length=191,
            ),
        ),
        migrations.AlterField(
            model_name="hubspotcontactsdatasync",
            name="hubspot_access_token",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The private app access token used to authenticate requests to HubSpot.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="jiraissuesdatasync",
            name="jira_api_token",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The API or personal access token of the Jira account used for authentication.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="openidconnectappauthprovidermodel",
            name="secret",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="API secret, client secret, or consumer secret",
                max_length=191,
            ),
        ),
        migrations.AlterField(
            model_name="openidconnectauthprovidermodel",
            name="secret",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="API secret, client secret, or consumer secret",
                max_length=191,
            ),
        ),
    ]
