# Generated by Django 5.2.16 on 2026-09-23 18:01

import baserow.contrib.database.webhooks.validators
import baserow.core.encryption.fields
import django.core.validators
from baserow.core.encryption.migration_operations import AddFieldIfNotExists
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0223_gridview_group_by_layout"),
    ]

    operations = [
        # The column exists already when upgrading from a release that encryption at
        # rest was backported to, see `AddFieldIfNotExists`.
        AddFieldIfNotExists(
            model_name="token",
            name="key_hash",
            field=models.CharField(
                editable=False,
                help_text="The SHA-256 hash of the key, used to find a token by key.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        # The existing keys are still in plain text, so their lookup hash can be
        # computed in the database. It must match `EncryptionHandler.hash_for_lookup`.
        migrations.RunSQL(
            sql=(
                "UPDATE database_token "
                "SET key_hash = encode(sha256(convert_to(key, 'UTF8')), 'hex') "
                "WHERE key_hash IS NULL AND left(key, 6) <> 'bxenc:'"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="airtableimportjob",
            name="session",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="Optionally provide a session object that's used as authentication.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="airtableimportjob",
            name="session_signature",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The matching session signature if a session is provided.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="postgresqldatasync",
            name="postgresql_password",
            field=baserow.core.encryption.fields.EncryptedTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tablewebhook",
            name="url",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The URL that must be called when the webhook is triggered.",
                validators=[
                    django.core.validators.MaxLengthValidator(2000),
                    baserow.contrib.database.webhooks.validators.url_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tablewebhookcall",
            name="called_url",
            field=baserow.core.encryption.fields.EncryptedTextField(
                validators=[
                    django.core.validators.MaxLengthValidator(2000),
                    baserow.contrib.database.webhooks.validators.url_validator,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tablewebhookcall",
            name="error",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="An internal error reflecting what went wrong.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tablewebhookcall",
            name="request",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="A text copy of the request headers and body.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tablewebhookcall",
            name="response",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="A text copy of the response headers and body.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tablewebhookheader",
            name="value",
            field=baserow.core.encryption.fields.EncryptedTextField(
                validators=[
                    baserow.contrib.database.webhooks.validators.header_value_validator
                ]
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="key",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The unique token key that can be used to authorize for the table row endpoints.",
                max_length=32,
            ),
        ),
    ]
