# Generated by Django 5.2.16 on 2026-09-23 18:01

import baserow.core.encryption.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0036_coreinboundemailtriggerservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiintegration",
            name="ai_settings",
            field=baserow.core.encryption.fields.EncryptedJSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="slackbotintegration",
            name="token",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The Bot User OAuth Token listed in your Slack bot's OAuth & Permissions page.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="smtpintegration",
            name="password",
            field=baserow.core.encryption.fields.EncryptedTextField(
                blank=True,
                help_text="The SMTP password for authentication.",
                max_length=255,
                null=True,
            ),
        ),
    ]
