# Generated by Django 5.2.15 on 2026-09-23 20:19

import baserow.core.encryption.fields
from baserow.core.encryption.migration_operations import AddFieldIfNotExists
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_alter_workspaceinvitation_message"),
    ]

    operations = [
        # An existing instance keeps writing secrets in plain text until every
        # instance runs this version and `./baserow encrypt_data` enables encryption,
        # so that the previous version can read everything during a rolling upgrade.
        # A new instance, without users yet, encrypts from the start. The columns
        # can exist already when upgrading from a release that encryption at rest
        # was backported to, see `AddFieldIfNotExists`.
        AddFieldIfNotExists(
            model_name="settings",
            name="encrypt_secrets_at_rest",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Indicates whether secrets are encrypted when they're written. It's disabled after upgrading an existing instance, so that the previous version can read them during a rolling upgrade, until the `encrypt_data` management command enables it.",
            ),
            sql_after_adding=(
                "UPDATE core_settings SET encrypt_secrets_at_rest = false "
                "WHERE EXISTS (SELECT 1 FROM auth_user)"
            ),
        ),
        AddFieldIfNotExists(
            model_name="mcpendpoint",
            name="key_hash",
            field=models.CharField(
                editable=False,
                help_text="The SHA-256 hash of the key, used to find an endpoint by key.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        # The existing keys are still in plain text, so their lookup hash can be
        # computed in the database. It must match `EncryptionHandler.hash_for_lookup`.
        migrations.RunSQL(
            sql=(
                "UPDATE core_mcpendpoint "
                "SET key_hash = encode(sha256(convert_to(key, 'UTF8')), 'hex') "
                "WHERE key_hash IS NULL AND left(key, 6) <> 'bxenc:'"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="importexporttrustedsource",
            name="private_key",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The private key used to sign the export."
            ),
        ),
        migrations.AlterField(
            model_name="mcpendpoint",
            name="key",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="The unique endpoint key that can be used to authorize for the MCP service.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="totpauthprovidermodel",
            name="provisioning_qr_code",
            field=baserow.core.encryption.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="totpauthprovidermodel",
            name="provisioning_url",
            field=baserow.core.encryption.fields.EncryptedTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="totpauthprovidermodel",
            name="secret",
            field=baserow.core.encryption.fields.EncryptedTextField(
                help_text="base32 secret", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="generative_ai_models_settings",
            field=baserow.core.encryption.fields.EncryptedJSONField(
                default=dict, null=True
            ),
        ),
    ]
